# Generated by Django 3.1 on 2020-10-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0116_rearport_max_positions'),
        ('extras', '0047_tag_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='configcontext',
            name='device_types',
            field=models.ManyToManyField(blank=True, related_name='_configcontext_device_types_+', to='dcim.DeviceType'),
        ),
    ]
